import code.modules.crosser as crosser
import code.StringToModel as StringToModel
import numpy as np
def crossover_population(population, crossings_number):
    """
    Perform a crossing operation for random pairs of superpositions stored in the
    'population'. The number of crossovers is determined by 'crossings_number'
    Inputs:
     config         - data structure storing MVR attributes

    Outputs:
     init_models    - handles of the initial models from the specified file (list of strings)
    """
    crossings_number = int(crossings_number)
    # superpositions generated by crossings
    new_generated_superpositions = []
    for i in range(crossings_number):
        models_to_cross = np.random.choice(population, 2)
        # extract handles
        models_to_cross = [obj.handle for obj in models_to_cross]
        int_pair_object = crosser.crossing(*models_to_cross)
        new_generated_superpositions.extend([int_pair_object.first, int_pair_object.second])

    # convert new strings to a population and append it to the existed one
    population.extend( StringToModel.strings_to_population(new_generated_superpositions) )
    return population